remote_theme: fancyoung/merlot
locale: "zh-CN"
navbar-links:
  home: "https://book.fancyoung.com/"
  blog: "https://fancyoung.com/"
social-network-links:
  github: fancyoung
disqus: "awesome-book"
plugins:
  - jekyll-sitemap
